import psycopg2

def create_tables(cur, connection1):
    
    """ create tables in Redshift"""
      
    commands = (
    """
    CREATE TABLE IF NOT EXISTS transaction(
      transaction_hash_id bigint,
      timestamp TIMESTAMP SORTKEY,
      store_id int,
      total_price FLOAT,
      payment_method varchar(250),
      PRIMARY KEY (transaction_hash_id)
    );
    """,
    
    
    """
    CREATE TABLE IF NOT EXISTS product(
      product_id INT GENERATED BY DEFAULT AS IDENTITY(1, 1),
      product_name varchar(250),
      price FLOAT,
      PRIMARY KEY (product_id)
    );
    """,
    
    """
    CREATE TABLE IF NOT EXISTS store(
      store_id INT GENERATED BY DEFAULT AS IDENTITY(1, 1),
      store_name varchar(250),
      PRIMARY KEY (store_id)
    );
    """,
    
    
    """
    CREATE TABLE IF NOT EXISTS basket(
      transaction_hash_id bigint,
      product_id int,
      quantity int
    );
    """)
    
    try:
        # create table one by one
        for command in commands:
            cur.execute(command)
        connection1.commit()
        print("Tables have been created.")
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)