on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  build-and-deploy:
    name: Deploy Terraform resources to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9"
      # - name: Run unit tests
      #   run: python -m pytest
      # - name: Zip up code in src folder for lambda deployment
      - name: Zip up src codes folder
        run: zip -r src.zip src
      
      - name: Zip up src load codes folder
        run: zip -r src_load.zip src_load  
      
      - name: list all files
        run: ls

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
